# Generated by Django 4.2 on 2023-04-25 15:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('equipment', '0002_alter_equipment_create_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_datetime', models.DateTimeField(default=datetime.datetime(2023, 4, 25, 22, 15, 6, 389797))),
                ('due_datetime', models.DateTimeField(default=datetime.datetime(2023, 4, 25, 22, 15, 6, 389797))),
                ('return_datetime', models.DateTimeField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.equipment')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
