# Generated by Django 4.2 on 2023-04-25 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='booking_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 22, 15, 12, 3343)),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='due_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 25, 22, 15, 12, 3343)),
        ),
    ]
