# Generated by Django 4.2 on 2023-04-20 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0002_alter_statistic_booking_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='booking_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 18, 35, 31, 11788)),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='due_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 18, 35, 31, 11788)),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='return_datetime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
