# Generated by Django 4.2 on 2023-04-20 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistic', '0003_alter_statistic_booking_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='booking_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 18, 37, 25, 92092)),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='due_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 27, 18, 37, 25, 92092)),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='return_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
