# Generated by Django 4.2 on 2023-04-19 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=1000)),
                ('pic', models.ImageField(upload_to='images/')),
                ('available', models.BooleanField(default=True)),
                ('own', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
