# Generated by Django 4.2 on 2023-04-23 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 1, 1, 22, 6, 683256)),
        ),
    ]
