# Generated by Django 4.2 on 2023-04-19 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('equipment', '0003_alter_equipment_own'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='own',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.student'),
        ),
    ]
