# Generated by Django 4.2 on 2023-04-30 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_equipment_create_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='create_datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 30, 22, 35, 42, 384933)),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='desc',
            field=models.TextField(max_length=1000),
        ),
    ]
